phrases = [
    "Wait and See",
    "Third Time Is the Charm",
    "The End Justifies the Means",
    "The Apple Doesnt Fall Far From the Tree",
    "Talk is Cheap",
    "Rome Wasnt Built in a Day",
    "Revenge Is a Dish Best Served Cold",
    "Pride Goes Before a Fall",
    "Only Fools and Horses Work",
    "Once Bitten Twice Shy",
    "No News is Good News",
    "No Man is an Island",
    "Misery Loves Company",
    "Might Is Right",
    "Less is More",
    "Its Never Too Late",
    "It Takes Two to Tango",
    "Ignorance is Bliss",
    "Hunger is the Best Sauce",
    "Haste Makes Waste",
    "Good Things Come to Those Who Wait",
    "Good Things Come in Threes",
    "Curiosity Killed the Cat",
    "Clothes Make the Man",
    "Blood is Thicker Than Water",
    "Better Late Than Never",
    "Bad News Travels Fast",
    "Bad Money Drives Out Good",
    "A Stitch in Time Saves Nine",
    "A Problem Shared is a Problem Halved",
    "A Picture Paints a Thousand Words",
    "A Penny Saved Is a Penny Earned",
    "A New Broom Sweeps Clean",
    "A House Divided Against Itself Cannot Stand",
    "A Good Man is Hard to Find",
    "A Friend in Need is a Friend Indeed",
    "A Fool and His Money Are Soon Parted",
    "A Bird in the Hand is Worth Two in the Bush"]
